[package]
name = "veternitzz/switch"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
description = "A switch implementation in pure luau."
realm = "shared"
exclude = ["**"]
include = ["switch.luau", "wally.toml"]

[dependencies]
