[package]
name = "veternitzz/switch"
version = "1.0.4"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
description = "A switch implementation in pure luau."
realm = "shared"
exclude = ["**"]
include = ["init.luau", "wally.toml"]

[dependencies]
